// @ts-nocheck
export const NOW_PLAYING_LINK_SELECTORS = [
    '.collection-item-container.playing a.item-link[href]',
    '.collection-item-container.track_play_hilite.playing a.item-link[href]',
    '.collection-item-container.track_play_hilite a.item-link[href]',
    '.play_status .fromAlbum a[href*="/album/"]',
    '.play_status .track-title a[href*="/track/"]',
    '#collection-player .fromAlbum a[href*="/album/"]',
    '#collection-player .track-title a[href*="/track/"]',
    '#track_play_waypoint a[href*="/album/"]',
    '#track_play_waypoint a[href*="/track/"]',
    '#footer-player a[href*="/album/"]',
    '#footer-player a[href*="/track/"]',
    '.playing_track a[href*="/album/"]',
    '.playing_track a[href*="/track/"]',
    '.story.playing a.item-link[href]',
    '.story-innards.playing a.item-link[href]',
    '.track_play_hilite.playing a.item-link[href]',
    '.track_play_waypoint.playing a.item-link[href]',
    '.recommended-item.track_play_hilite a[href*="/album/"]',
    '.recommended-item.track_play_hilite a[href*="/track/"]',
    '.recommended-grid-item.track_play_hilite a[href*="/album/"]',
    '.recommended-grid-item.track_play_hilite a[href*="/track/"]',
    '.recommended-album-item.track_play_hilite a[href*="/album/"]',
    '.recommended-album-item.track_play_hilite a[href*="/track/"]',
    '.discover-player a[href*="/album/"]',
    '.discover-player a[href*="/track/"]',
    '#discover-player a[href*="/album/"]',
    '#discover-player a[href*="/track/"]',
    '.player-top a[href*="/album/"]',
    '.player-top a[href*="/track/"]',
    '.player-info a[href*="/album/"]',
    '.player-info a[href*="/track/"]'
];
export const NOW_PLAYING_IDENTITY_SELECTORS = [
    '.collection-item-container.playing a.item-link[href]',
    '.collection-item-container.track_play_hilite.playing a.item-link[href]',
    '.collection-item-container.track_play_hilite a.item-link[href]',
    '.play_status .fromAlbum a[href]',
    '.play_status .track-title a[href]',
    '#collection-player .fromAlbum a[href]',
    '#collection-player .track-title a[href]',
    '#track_play_waypoint a[href]',
    '#footer-player a[href]',
    '.playing_track a[href]',
    '.story.playing a.item-link[href]',
    '.story-innards.playing a.item-link[href]',
    '.track_play_hilite.playing a.item-link[href]',
    '.track_play_waypoint.playing a.item-link[href]',
    '.recommended-item.track_play_hilite a[href]',
    '.recommended-grid-item.track_play_hilite a[href]',
    '.recommended-album-item.track_play_hilite a[href]',
    '.discover-player a[href*="/album/"]',
    '.discover-player a[href*="/track/"]',
    '#discover-player a[href*="/album/"]',
    '#discover-player a[href*="/track/"]',
    '.player-top a[href*="/album/"]',
    '.player-top a[href*="/track/"]',
    '.player-info a[href*="/album/"]',
    '.player-info a[href*="/track/"]'
];
export const NOW_PLAYING_DEBUG_SELECTORS = [
    '.collection-item-container.playing a.item-link[href]',
    '.collection-item-container.track_play_hilite.playing a.item-link[href]',
    '.collection-item-container.track_play_hilite a.item-link[href]',
    '.play_status .fromAlbum a[href]',
    '.play_status .track-title a[href]',
    '#collection-player .fromAlbum a[href]',
    '#collection-player .track-title a[href]',
    '#track_play_waypoint a[href]',
    '#footer-player a[href]',
    '.playing_track a[href]',
    '.story.playing a.item-link[href]',
    '.story-innards.playing a.item-link[href]',
    '.track_play_hilite.playing a.item-link[href]',
    '.track_play_waypoint.playing a.item-link[href]',
    '.recommended-item.track_play_hilite a[href]',
    '.recommended-grid-item.track_play_hilite a[href]',
    '.recommended-album-item.track_play_hilite a[href]'
];
export const DOM_IDENTITY_QUERY_ATTR_SELECTORS = [
    '[data-item-id]',
    '[data-itemid]',
    '[data-item_id]',
    '[data-tralbum-id]',
    '[data-tralbumid]',
    '[data-tralbum_id]',
    '[data-track-id]',
    '[data-trackid]',
    '[data-track_id]',
    '[data-band-id]',
    '[data-bandid]',
    '[data-band_id]',
    '[data-selling-band-id]',
    '[data-selling_band_id]'
];
export const DOM_DEBUG_QUERY_ATTR_SELECTORS = [
    '[data-item-id]',
    '[data-itemid]',
    '[data-item_id]',
    '[data-tralbum-id]',
    '[data-tralbumid]',
    '[data-tralbum_id]',
    '[data-track-id]',
    '[data-trackid]',
    '[data-track_id]',
    '[data-band-id]',
    '[data-bandid]',
    '[data-band_id]',
    '[data-item-type]',
    '[data-itemtype]',
    '[data-item_type]',
    '[data-tralbum-type]',
    '[data-tralbum_type]'
];
export const DOM_DEBUG_INTERESTING_ATTRS = [
    'data-item-id',
    'data-itemid',
    'data-item_id',
    'data-tralbum-id',
    'data-tralbumid',
    'data-tralbum_id',
    'data-album-id',
    'data-albumid',
    'data-album_id',
    'data-track-id',
    'data-trackid',
    'data-track_id',
    'data-band-id',
    'data-bandid',
    'data-band_id',
    'data-selling-band-id',
    'data-selling_band_id',
    'data-item-type',
    'data-itemtype',
    'data-item_type',
    'data-tralbum-type',
    'data-tralbum_type'
];
